export interface CountryOption {
  code: string;
  name: string;
  region: string;
  flagSvgUrl?: string;
  flagPngUrl?: string;
}

const popularCountryOptions: CountryOption[] = [
  { code: "ID", name: "Indonesia", region: "Asia" },
  { code: "BR", name: "Brazil", region: "South America" },
  { code: "ES", name: "Spain", region: "Europe" },
  { code: "NL", name: "Netherlands", region: "Europe" },
  { code: "PH", name: "Philippines", region: "Asia" },
  { code: "IQ", name: "Iraq", region: "Asia" },
  { code: "CM", name: "Cameroon", region: "Africa" },
  { code: "AR", name: "Argentina", region: "South America" },
  { code: "JP", name: "Japan", region: "Asia" },
  { code: "KR", name: "South Korea", region: "Asia" },
  { code: "TH", name: "Thailand", region: "Asia" },
  { code: "MY", name: "Malaysia", region: "Asia" },
  { code: "SG", name: "Singapore", region: "Asia" },
  { code: "VN", name: "Vietnam", region: "Asia" },
  { code: "AU", name: "Australia", region: "Oceania" },
  { code: "PT", name: "Portugal", region: "Europe" },
  { code: "FR", name: "France", region: "Europe" },
  { code: "DE", name: "Germany", region: "Europe" },
  { code: "IT", name: "Italy", region: "Europe" },
  { code: "GB", name: "United Kingdom", region: "Europe" },
  { code: "US", name: "United States", region: "North America" },
  { code: "UY", name: "Uruguay", region: "South America" },
  { code: "CO", name: "Colombia", region: "South America" },
  { code: "CL", name: "Chile", region: "South America" },
  { code: "MX", name: "Mexico", region: "North America" },
  { code: "NG", name: "Nigeria", region: "Africa" },
  { code: "GH", name: "Ghana", region: "Africa" },
  { code: "SN", name: "Senegal", region: "Africa" },
  { code: "ML", name: "Mali", region: "Africa" },
];

const isoCountryCodes = [
  "AD",
  "AE",
  "AF",
  "AG",
  "AI",
  "AL",
  "AM",
  "AO",
  "AQ",
  "AR",
  "AS",
  "AT",
  "AU",
  "AW",
  "AX",
  "AZ",
  "BA",
  "BB",
  "BD",
  "BE",
  "BF",
  "BG",
  "BH",
  "BI",
  "BJ",
  "BL",
  "BM",
  "BN",
  "BO",
  "BQ",
  "BR",
  "BS",
  "BT",
  "BV",
  "BW",
  "BY",
  "BZ",
  "CA",
  "CC",
  "CD",
  "CF",
  "CG",
  "CH",
  "CI",
  "CK",
  "CL",
  "CM",
  "CN",
  "CO",
  "CR",
  "CU",
  "CV",
  "CW",
  "CX",
  "CY",
  "CZ",
  "DE",
  "DJ",
  "DK",
  "DM",
  "DO",
  "DZ",
  "EC",
  "EE",
  "EG",
  "EH",
  "ER",
  "ES",
  "ET",
  "FI",
  "FJ",
  "FK",
  "FM",
  "FO",
  "FR",
  "GA",
  "GB",
  "GD",
  "GE",
  "GF",
  "GG",
  "GH",
  "GI",
  "GL",
  "GM",
  "GN",
  "GP",
  "GQ",
  "GR",
  "GS",
  "GT",
  "GU",
  "GW",
  "GY",
  "HK",
  "HM",
  "HN",
  "HR",
  "HT",
  "HU",
  "ID",
  "IE",
  "IL",
  "IM",
  "IN",
  "IO",
  "IQ",
  "IR",
  "IS",
  "IT",
  "JE",
  "JM",
  "JO",
  "JP",
  "KE",
  "KG",
  "KH",
  "KI",
  "KM",
  "KN",
  "KP",
  "KR",
  "KW",
  "KY",
  "KZ",
  "LA",
  "LB",
  "LC",
  "LI",
  "LK",
  "LR",
  "LS",
  "LT",
  "LU",
  "LV",
  "LY",
  "MA",
  "MC",
  "MD",
  "ME",
  "MF",
  "MG",
  "MH",
  "MK",
  "ML",
  "MM",
  "MN",
  "MO",
  "MP",
  "MQ",
  "MR",
  "MS",
  "MT",
  "MU",
  "MV",
  "MW",
  "MX",
  "MY",
  "MZ",
  "NA",
  "NC",
  "NE",
  "NF",
  "NG",
  "NI",
  "NL",
  "NO",
  "NP",
  "NR",
  "NU",
  "NZ",
  "OM",
  "PA",
  "PE",
  "PF",
  "PG",
  "PH",
  "PK",
  "PL",
  "PM",
  "PN",
  "PR",
  "PS",
  "PT",
  "PW",
  "PY",
  "QA",
  "RE",
  "RO",
  "RS",
  "RU",
  "RW",
  "SA",
  "SB",
  "SC",
  "SD",
  "SE",
  "SG",
  "SH",
  "SI",
  "SJ",
  "SK",
  "SL",
  "SM",
  "SN",
  "SO",
  "SR",
  "SS",
  "ST",
  "SV",
  "SX",
  "SY",
  "SZ",
  "TC",
  "TD",
  "TF",
  "TG",
  "TH",
  "TJ",
  "TK",
  "TL",
  "TM",
  "TN",
  "TO",
  "TR",
  "TT",
  "TV",
  "TW",
  "TZ",
  "UA",
  "UG",
  "UM",
  "US",
  "UY",
  "UZ",
  "VA",
  "VC",
  "VE",
  "VG",
  "VI",
  "VN",
  "VU",
  "WF",
  "WS",
  "YE",
  "YT",
  "ZA",
  "ZM",
  "ZW",
] as const;

const stableCountryNames: Record<string, string> = {
  AD: "Andorra",
  AE: "United Arab Emirates",
  AF: "Afghanistan",
  AG: "Antigua and Barbuda",
  AI: "Anguilla",
  AL: "Albania",
  AM: "Armenia",
  AO: "Angola",
  AQ: "Antarctica",
  AS: "American Samoa",
  AT: "Austria",
  AW: "Aruba",
  AX: "Aland Islands",
  AZ: "Azerbaijan",
  BA: "Bosnia and Herzegovina",
  BB: "Barbados",
  BD: "Bangladesh",
  BE: "Belgium",
  BF: "Burkina Faso",
  BG: "Bulgaria",
  BH: "Bahrain",
  BI: "Burundi",
  BJ: "Benin",
  BL: "Saint Barthelemy",
  BM: "Bermuda",
  BN: "Brunei",
  BO: "Bolivia",
  BQ: "Caribbean Netherlands",
  BS: "Bahamas",
  BT: "Bhutan",
  BV: "Bouvet Island",
  BW: "Botswana",
  BY: "Belarus",
  BZ: "Belize",
  CA: "Canada",
  CC: "Cocos Islands",
  CD: "DR Congo",
  CF: "Central African Republic",
  CG: "Congo",
  CH: "Switzerland",
  CI: "Ivory Coast",
  CK: "Cook Islands",
  CN: "China",
  CR: "Costa Rica",
  CU: "Cuba",
  CV: "Cape Verde",
  CW: "Curacao",
  CX: "Christmas Island",
  CY: "Cyprus",
  CZ: "Czechia",
  DJ: "Djibouti",
  DK: "Denmark",
  DM: "Dominica",
  DO: "Dominican Republic",
  DZ: "Algeria",
  EC: "Ecuador",
  EE: "Estonia",
  EG: "Egypt",
  EH: "Western Sahara",
  ER: "Eritrea",
  ET: "Ethiopia",
  FI: "Finland",
  FJ: "Fiji",
  FK: "Falkland Islands",
  FM: "Micronesia",
  FO: "Faroe Islands",
  GA: "Gabon",
  GD: "Grenada",
  GE: "Georgia",
  GF: "French Guiana",
  GG: "Guernsey",
  GI: "Gibraltar",
  GL: "Greenland",
  GM: "Gambia",
  GN: "Guinea",
  GP: "Guadeloupe",
  GQ: "Equatorial Guinea",
  GR: "Greece",
  GS: "South Georgia",
  GT: "Guatemala",
  GU: "Guam",
  GW: "Guinea-Bissau",
  GY: "Guyana",
  HK: "Hong Kong",
  HM: "Heard Island and McDonald Islands",
  HN: "Honduras",
  HR: "Croatia",
  HT: "Haiti",
  HU: "Hungary",
  IE: "Ireland",
  IL: "Israel",
  IM: "Isle of Man",
  IN: "India",
  IO: "British Indian Ocean Territory",
  IR: "Iran",
  IS: "Iceland",
  JE: "Jersey",
  JM: "Jamaica",
  JO: "Jordan",
  KE: "Kenya",
  KG: "Kyrgyzstan",
  KH: "Cambodia",
  KI: "Kiribati",
  KM: "Comoros",
  KN: "Saint Kitts and Nevis",
  KP: "North Korea",
  KW: "Kuwait",
  KY: "Cayman Islands",
  KZ: "Kazakhstan",
  LA: "Laos",
  LB: "Lebanon",
  LC: "Saint Lucia",
  LI: "Liechtenstein",
  LK: "Sri Lanka",
  LR: "Liberia",
  LS: "Lesotho",
  LT: "Lithuania",
  LU: "Luxembourg",
  LV: "Latvia",
  LY: "Libya",
  MA: "Morocco",
  MC: "Monaco",
  MD: "Moldova",
  ME: "Montenegro",
  MF: "Saint Martin",
  MG: "Madagascar",
  MH: "Marshall Islands",
  MK: "North Macedonia",
  MM: "Myanmar",
  MN: "Mongolia",
  MO: "Macao",
  MP: "Northern Mariana Islands",
  MQ: "Martinique",
  MR: "Mauritania",
  MS: "Montserrat",
  MT: "Malta",
  MU: "Mauritius",
  MV: "Maldives",
  MW: "Malawi",
  MZ: "Mozambique",
  NA: "Namibia",
  NC: "New Caledonia",
  NE: "Niger",
  NF: "Norfolk Island",
  NI: "Nicaragua",
  NO: "Norway",
  NP: "Nepal",
  NR: "Nauru",
  NU: "Niue",
  NZ: "New Zealand",
  OM: "Oman",
  PA: "Panama",
  PE: "Peru",
  PF: "French Polynesia",
  PG: "Papua New Guinea",
  PK: "Pakistan",
  PL: "Poland",
  PM: "Saint Pierre and Miquelon",
  PN: "Pitcairn Islands",
  PR: "Puerto Rico",
  PS: "Palestine",
  PW: "Palau",
  PY: "Paraguay",
  QA: "Qatar",
  RE: "Reunion",
  RO: "Romania",
  RS: "Serbia",
  RU: "Russia",
  RW: "Rwanda",
  SA: "Saudi Arabia",
  SB: "Solomon Islands",
  SC: "Seychelles",
  SD: "Sudan",
  SE: "Sweden",
  SH: "Saint Helena",
  SI: "Slovenia",
  SJ: "Svalbard and Jan Mayen",
  SK: "Slovakia",
  SL: "Sierra Leone",
  SM: "San Marino",
  SO: "Somalia",
  SR: "Suriname",
  SS: "South Sudan",
  ST: "Sao Tome and Principe",
  SV: "El Salvador",
  SX: "Sint Maarten",
  SY: "Syria",
  SZ: "Eswatini",
  TC: "Turks and Caicos Islands",
  TD: "Chad",
  TF: "French Southern Territories",
  TG: "Togo",
  TJ: "Tajikistan",
  TK: "Tokelau",
  TL: "Timor-Leste",
  TM: "Turkmenistan",
  TN: "Tunisia",
  TO: "Tonga",
  TR: "Turkey",
  TT: "Trinidad and Tobago",
  TV: "Tuvalu",
  TW: "Taiwan",
  TZ: "Tanzania",
  UA: "Ukraine",
  UG: "Uganda",
  UM: "US Outlying Islands",
  UZ: "Uzbekistan",
  VA: "Vatican City",
  VC: "Saint Vincent and the Grenadines",
  VE: "Venezuela",
  VG: "British Virgin Islands",
  VI: "US Virgin Islands",
  VU: "Vanuatu",
  WF: "Wallis and Futuna",
  WS: "Samoa",
  YE: "Yemen",
  YT: "Mayotte",
  ZA: "South Africa",
  ZM: "Zambia",
  ZW: "Zimbabwe",
};

export function getFlagCdnSvgUrl(countryCode: string) {
  const code = countryCode.toLowerCase();

  if (!/^[a-z]{2}$/.test(code)) {
    return undefined;
  }

  return `https://flagcdn.com/${code}.svg`;
}

const generatedCountryOptions: CountryOption[] = isoCountryCodes.map((code) => ({
  code,
  name: stableCountryNames[code] ?? code,
  region: "All Countries",
  flagSvgUrl: getFlagCdnSvgUrl(code),
}));

export const countryOptions: CountryOption[] = [
  ...popularCountryOptions,
  ...generatedCountryOptions.filter(
    (country) =>
      !popularCountryOptions.some(
        (popularCountry) => popularCountry.code === country.code,
      ),
  ),
].map((country) => ({
  ...country,
  flagSvgUrl: country.flagSvgUrl ?? getFlagCdnSvgUrl(country.code),
}));

export const flagStyles: Record<string, string> = {
  AR: "bg-[linear-gradient(180deg,#74acdf_0_33%,#fff_33%_66%,#74acdf_66%)]",
  AU: "bg-[#00008b]",
  BR: "bg-[#009739] after:absolute after:left-1/2 after:top-1/2 after:h-[62%] after:w-[62%] after:-translate-x-1/2 after:-translate-y-1/2 after:rotate-45 after:bg-[#ffdf00] before:absolute before:left-1/2 before:top-1/2 before:h-[34%] before:w-[34%] before:-translate-x-1/2 before:-translate-y-1/2 before:rounded-full before:bg-[#002776]",
  CL: "bg-[linear-gradient(180deg,#fff_0_50%,#d52b1e_50%)] before:absolute before:left-0 before:top-0 before:h-1/2 before:w-2/5 before:bg-[#0039a6]",
  CM: "bg-[linear-gradient(90deg,#007a5e_0_33%,#ce1126_33%_66%,#fcd116_66%)]",
  CO: "bg-[linear-gradient(180deg,#fcd116_0_50%,#003893_50%_75%,#ce1126_75%)]",
  DE: "bg-[linear-gradient(180deg,#000_0_33%,#dd0000_33%_66%,#ffce00_66%)]",
  ES: "bg-[linear-gradient(180deg,#aa151b_0_25%,#f1bf00_25%_75%,#aa151b_75%)]",
  FR: "bg-[linear-gradient(90deg,#002395_0_33%,#fff_33%_66%,#ed2939_66%)]",
  GB: "bg-[linear-gradient(90deg,#012169,#012169)] before:absolute before:inset-y-0 before:left-1/2 before:w-[18%] before:-translate-x-1/2 before:bg-white after:absolute after:inset-x-0 after:top-1/2 after:h-[18%] after:-translate-y-1/2 after:bg-white",
  GH: "bg-[linear-gradient(180deg,#ce1126_0_33%,#fcd116_33%_66%,#006b3f_66%)]",
  ID: "bg-[linear-gradient(180deg,#ef4444_0_50%,#fff_50%)]",
  IQ: "bg-[linear-gradient(180deg,#ce1126_0_33%,#fff_33%_66%,#000_66%)]",
  IT: "bg-[linear-gradient(90deg,#009246_0_33%,#fff_33%_66%,#ce2b37_66%)]",
  JP: "bg-white before:absolute before:left-1/2 before:top-1/2 before:h-[48%] before:w-[48%] before:-translate-x-1/2 before:-translate-y-1/2 before:rounded-full before:bg-[#bc002d]",
  KR: "bg-white before:absolute before:left-1/2 before:top-1/2 before:h-[44%] before:w-[44%] before:-translate-x-1/2 before:-translate-y-1/2 before:rounded-full before:bg-[linear-gradient(180deg,#cd2e3a_0_50%,#0047a0_50%)]",
  ML: "bg-[linear-gradient(90deg,#14b53a_0_33%,#fcd116_33%_66%,#ce1126_66%)]",
  MX: "bg-[linear-gradient(90deg,#006847_0_33%,#fff_33%_66%,#ce1126_66%)]",
  MY: "bg-[linear-gradient(180deg,#cc0001_0_14%,#fff_14%_28%,#cc0001_28%_42%,#fff_42%_56%,#cc0001_56%_70%,#fff_70%_84%,#cc0001_84%)] before:absolute before:left-0 before:top-0 before:h-[58%] before:w-[48%] before:bg-[#010066]",
  NG: "bg-[linear-gradient(90deg,#008751_0_33%,#fff_33%_66%,#008751_66%)]",
  NL: "bg-[linear-gradient(180deg,#ae1c28_0_33%,#fff_33%_66%,#21468b_66%)]",
  PH: "bg-[linear-gradient(180deg,#0038a8_0_50%,#ce1126_50%)] before:absolute before:left-0 before:top-0 before:h-full before:w-[45%] before:[clip-path:polygon(0_0,100%_50%,0_100%)] before:bg-white",
  PT: "bg-[linear-gradient(90deg,#006600_0_42%,#ff0000_42%)]",
  SG: "bg-[linear-gradient(180deg,#ef3340_0_50%,#fff_50%)]",
  SN: "bg-[linear-gradient(90deg,#00853f_0_33%,#fdef42_33%_66%,#e31b23_66%)]",
  TH: "bg-[linear-gradient(180deg,#a51931_0_16%,#fff_16%_32%,#2d2a4a_32%_68%,#fff_68%_84%,#a51931_84%)]",
  US: "bg-[linear-gradient(180deg,#b22234_0_14%,#fff_14%_28%,#b22234_28%_42%,#fff_42%_56%,#b22234_56%_70%,#fff_70%_84%,#b22234_84%)] before:absolute before:left-0 before:top-0 before:h-[54%] before:w-[45%] before:bg-[#3c3b6e]",
  UY: "bg-[linear-gradient(180deg,#fff_0_14%,#0038a8_14%_28%,#fff_28%_42%,#0038a8_42%_56%,#fff_56%_70%,#0038a8_70%_84%,#fff_84%)]",
  VN: "bg-[#da251d]",
};

export const countryNameToCode: Record<string, string> = {
  AMERIKA_SERIKAT: "US",
  ARGENTINA: "AR",
  AUSTRALIA: "AU",
  BELANDA: "NL",
  BRAZIL: "BR",
  CAMEROON: "CM",
  CHILE: "CL",
  COLOMBIA: "CO",
  GHANA: "GH",
  INDONESIA: "ID",
  INGGRIS: "GB",
  IRAK: "IQ",
  IRAQ: "IQ",
  ITALIA: "IT",
  JEPANG: "JP",
  JERMAN: "DE",
  KAMERUN: "CM",
  KOLUMBIA: "CO",
  KOREA_SELATAN: "KR",
  KOSTA_RIKA: "CR",
  LUKSEMBURG: "LU",
  LUXEMBOURG: "LU",
  MALI: "ML",
  MALAYSIA: "MY",
  MEKSIKO: "MX",
  MONTENEGRO: "ME",
  NIGERIA: "NG",
  PERANCIS: "FR",
  PORTUGAL: "PT",
  SENEGAL: "SN",
  SINGAPURA: "SG",
  SPANYOL: "ES",
  THAILAND: "TH",
  URUGUAY: "UY",
  VIETNAM: "VN",
};

export function getCountryCodeFromName(countryName: string) {
  const key = countryName
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .trim()
    .toUpperCase()
    .replace(/[^A-Z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");

  return countryNameToCode[key] ?? key.slice(0, 2);
}
