import type {
  FormationCoordinate,
  FormationName,
  FormationTemplate,
  MatchdayLineupData,
  MatchResultData,
  Player,
  PlayerPosition,
  TeamLineup,
  TransferRumorData,
} from "@/types/gosball";
import { competitionMasters } from "@/lib/competitions";

const coordinate = (
  id: string,
  label: string,
  position: PlayerPosition,
  x: number,
  y: number,
): FormationCoordinate => ({
  id,
  label,
  position,
  x,
  y,
});

const player = (
  id: string,
  shirtNumber: number,
  name: string,
  position: PlayerPosition,
  flagEmoji = "🇮🇩",
  nationality = "Indonesia",
  countryCode = "ID",
): Player => ({
  id,
  name,
  position,
  nationality,
  countryCode,
  flagEmoji,
  isForeign: nationality !== "Indonesia",
  shirtNumber,
});

export const formationOptions: FormationName[] = [
  "4-3-3",
  "4-2-3-1",
  "4-4-2",
  "4-1-4-1",
  "4-3-2-1",
  "4-3-1-2",
  "4-5-1",
  "4-1-2-1-2",
  "4-2-2-2",
  "4-4-1-1",
  "3-5-2",
  "3-1-4-2",
  "3-4-3",
  "3-4-2-1",
  "3-4-1-2",
  "5-3-2",
  "5-2-3",
  "5-4-1",
];

export const formationTemplates: Record<FormationName, FormationTemplate> = {
  "4-3-3": {
    name: "4-3-3",
    coordinates: [
      coordinate("gk", "GK", "GK", 50, 88),
      coordinate("lb", "LB", "DF", 18, 68),
      coordinate("lcb", "CB", "DF", 38, 70),
      coordinate("rcb", "CB", "DF", 62, 70),
      coordinate("rb", "RB", "DF", 82, 68),
      coordinate("lcm", "CM", "MF", 28, 48),
      coordinate("dm", "DM", "MF", 50, 53),
      coordinate("rcm", "CM", "MF", 72, 48),
      coordinate("lw", "LW", "FW", 18, 26),
      coordinate("st", "ST", "FW", 50, 18),
      coordinate("rw", "RW", "FW", 82, 26),
    ],
  },
  "4-2-3-1": {
    name: "4-2-3-1",
    coordinates: [
      coordinate("gk", "GK", "GK", 50, 88),
      coordinate("lb", "LB", "DF", 18, 68),
      coordinate("lcb", "CB", "DF", 38, 70),
      coordinate("rcb", "CB", "DF", 62, 70),
      coordinate("rb", "RB", "DF", 82, 68),
      coordinate("ldm", "DM", "MF", 38, 53),
      coordinate("rdm", "DM", "MF", 62, 53),
      coordinate("lam", "AM", "MF", 24, 35),
      coordinate("cam", "AM", "MF", 50, 32),
      coordinate("ram", "AM", "MF", 76, 35),
      coordinate("st", "ST", "FW", 50, 16),
    ],
  },
  "4-4-2": {
    name: "4-4-2",
    coordinates: [
      coordinate("gk", "GK", "GK", 50, 88),
      coordinate("lb", "LB", "DF", 18, 68),
      coordinate("lcb", "CB", "DF", 38, 70),
      coordinate("rcb", "CB", "DF", 62, 70),
      coordinate("rb", "RB", "DF", 82, 68),
      coordinate("lm", "LM", "MF", 18, 47),
      coordinate("lcm", "CM", "MF", 38, 50),
      coordinate("rcm", "CM", "MF", 62, 50),
      coordinate("rm", "RM", "MF", 82, 47),
      coordinate("lst", "ST", "FW", 40, 20),
      coordinate("rst", "ST", "FW", 60, 20),
    ],
  },
  "4-1-4-1": {
    name: "4-1-4-1",
    coordinates: [
      coordinate("gk", "GK", "GK", 50, 88),
      coordinate("lb", "LB", "DF", 18, 68),
      coordinate("lcb", "CB", "DF", 38, 70),
      coordinate("rcb", "CB", "DF", 62, 70),
      coordinate("rb", "RB", "DF", 82, 68),
      coordinate("dm", "DM", "MF", 50, 55),
      coordinate("lm", "LM", "MF", 18, 39),
      coordinate("lcm", "CM", "MF", 38, 42),
      coordinate("rcm", "CM", "MF", 62, 42),
      coordinate("rm", "RM", "MF", 82, 39),
      coordinate("st", "ST", "FW", 50, 17),
    ],
  },
  "4-3-2-1": {
    name: "4-3-2-1",
    coordinates: [
      coordinate("gk", "GK", "GK", 50, 88),
      coordinate("lb", "LB", "DF", 18, 68),
      coordinate("lcb", "CB", "DF", 38, 70),
      coordinate("rcb", "CB", "DF", 62, 70),
      coordinate("rb", "RB", "DF", 82, 68),
      coordinate("lcm", "CM", "MF", 28, 50),
      coordinate("dm", "DM", "MF", 50, 54),
      coordinate("rcm", "CM", "MF", 72, 50),
      coordinate("lam", "AM", "MF", 38, 33),
      coordinate("ram", "AM", "MF", 62, 33),
      coordinate("st", "ST", "FW", 50, 16),
    ],
  },
  "4-3-1-2": {
    name: "4-3-1-2",
    coordinates: [
      coordinate("gk", "GK", "GK", 50, 88),
      coordinate("lb", "LB", "DF", 18, 68),
      coordinate("lcb", "CB", "DF", 38, 70),
      coordinate("rcb", "CB", "DF", 62, 70),
      coordinate("rb", "RB", "DF", 82, 68),
      coordinate("lcm", "CM", "MF", 28, 50),
      coordinate("dm", "DM", "MF", 50, 54),
      coordinate("rcm", "CM", "MF", 72, 50),
      coordinate("cam", "AM", "MF", 50, 35),
      coordinate("lst", "ST", "FW", 40, 18),
      coordinate("rst", "ST", "FW", 60, 18),
    ],
  },
  "4-5-1": {
    name: "4-5-1",
    coordinates: [
      coordinate("gk", "GK", "GK", 50, 88),
      coordinate("lb", "LB", "DF", 18, 68),
      coordinate("lcb", "CB", "DF", 38, 70),
      coordinate("rcb", "CB", "DF", 62, 70),
      coordinate("rb", "RB", "DF", 82, 68),
      coordinate("lm", "LM", "MF", 14, 43),
      coordinate("lcm", "CM", "MF", 32, 48),
      coordinate("cm", "CM", "MF", 50, 51),
      coordinate("rcm", "CM", "MF", 68, 48),
      coordinate("rm", "RM", "MF", 86, 43),
      coordinate("st", "ST", "FW", 50, 17),
    ],
  },
  "4-1-2-1-2": {
    name: "4-1-2-1-2",
    coordinates: [
      coordinate("gk", "GK", "GK", 50, 88),
      coordinate("lb", "LB", "DF", 18, 68),
      coordinate("lcb", "CB", "DF", 38, 70),
      coordinate("rcb", "CB", "DF", 62, 70),
      coordinate("rb", "RB", "DF", 82, 68),
      coordinate("dm", "DM", "MF", 50, 56),
      coordinate("lcm", "CM", "MF", 34, 45),
      coordinate("rcm", "CM", "MF", 66, 45),
      coordinate("cam", "AM", "MF", 50, 34),
      coordinate("lst", "ST", "FW", 40, 18),
      coordinate("rst", "ST", "FW", 60, 18),
    ],
  },
  "4-2-2-2": {
    name: "4-2-2-2",
    coordinates: [
      coordinate("gk", "GK", "GK", 50, 88),
      coordinate("lb", "LB", "DF", 18, 68),
      coordinate("lcb", "CB", "DF", 38, 70),
      coordinate("rcb", "CB", "DF", 62, 70),
      coordinate("rb", "RB", "DF", 82, 68),
      coordinate("ldm", "DM", "MF", 38, 54),
      coordinate("rdm", "DM", "MF", 62, 54),
      coordinate("lam", "AM", "MF", 34, 36),
      coordinate("ram", "AM", "MF", 66, 36),
      coordinate("lst", "ST", "FW", 40, 18),
      coordinate("rst", "ST", "FW", 60, 18),
    ],
  },
  "4-4-1-1": {
    name: "4-4-1-1",
    coordinates: [
      coordinate("gk", "GK", "GK", 50, 88),
      coordinate("lb", "LB", "DF", 18, 68),
      coordinate("lcb", "CB", "DF", 38, 70),
      coordinate("rcb", "CB", "DF", 62, 70),
      coordinate("rb", "RB", "DF", 82, 68),
      coordinate("lm", "LM", "MF", 18, 47),
      coordinate("lcm", "CM", "MF", 38, 50),
      coordinate("rcm", "CM", "MF", 62, 50),
      coordinate("rm", "RM", "MF", 82, 47),
      coordinate("ss", "SS", "FW", 50, 31),
      coordinate("st", "ST", "FW", 50, 17),
    ],
  },
  "3-5-2": {
    name: "3-5-2",
    coordinates: [
      coordinate("gk", "GK", "GK", 50, 88),
      coordinate("lcb", "CB", "DF", 30, 70),
      coordinate("cb", "CB", "DF", 50, 73),
      coordinate("rcb", "CB", "DF", 70, 70),
      coordinate("lwb", "WB", "MF", 16, 50),
      coordinate("lcm", "CM", "MF", 36, 48),
      coordinate("cm", "CM", "MF", 50, 42),
      coordinate("rcm", "CM", "MF", 64, 48),
      coordinate("rwb", "WB", "MF", 84, 50),
      coordinate("lst", "ST", "FW", 40, 20),
      coordinate("rst", "ST", "FW", 60, 20),
    ],
  },
  "3-1-4-2": {
    name: "3-1-4-2",
    coordinates: [
      coordinate("gk", "GK", "GK", 50, 88),
      coordinate("lcb", "CB", "DF", 30, 70),
      coordinate("cb", "CB", "DF", 50, 73),
      coordinate("rcb", "CB", "DF", 70, 70),
      coordinate("dm", "DM", "MF", 50, 58),
      coordinate("lm", "LM", "MF", 18, 44),
      coordinate("lcm", "CM", "MF", 40, 46),
      coordinate("rcm", "CM", "MF", 60, 46),
      coordinate("rm", "RM", "MF", 82, 44),
      coordinate("lst", "ST", "FW", 40, 20),
      coordinate("rst", "ST", "FW", 60, 20),
    ],
  },
  "3-4-3": {
    name: "3-4-3",
    coordinates: [
      coordinate("gk", "GK", "GK", 50, 88),
      coordinate("lcb", "CB", "DF", 30, 70),
      coordinate("cb", "CB", "DF", 50, 73),
      coordinate("rcb", "CB", "DF", 70, 70),
      coordinate("lm", "LM", "MF", 18, 49),
      coordinate("lcm", "CM", "MF", 40, 51),
      coordinate("rcm", "CM", "MF", 60, 51),
      coordinate("rm", "RM", "MF", 82, 49),
      coordinate("lw", "LW", "FW", 20, 24),
      coordinate("st", "ST", "FW", 50, 17),
      coordinate("rw", "RW", "FW", 80, 24),
    ],
  },
  "3-4-2-1": {
    name: "3-4-2-1",
    coordinates: [
      coordinate("gk", "GK", "GK", 50, 88),
      coordinate("lcb", "CB", "DF", 30, 70),
      coordinate("cb", "CB", "DF", 50, 73),
      coordinate("rcb", "CB", "DF", 70, 70),
      coordinate("lm", "LM", "MF", 18, 50),
      coordinate("lcm", "CM", "MF", 40, 52),
      coordinate("rcm", "CM", "MF", 60, 52),
      coordinate("rm", "RM", "MF", 82, 50),
      coordinate("lam", "AM", "MF", 38, 33),
      coordinate("ram", "AM", "MF", 62, 33),
      coordinate("st", "ST", "FW", 50, 16),
    ],
  },
  "3-4-1-2": {
    name: "3-4-1-2",
    coordinates: [
      coordinate("gk", "GK", "GK", 50, 88),
      coordinate("lcb", "CB", "DF", 30, 70),
      coordinate("cb", "CB", "DF", 50, 73),
      coordinate("rcb", "CB", "DF", 70, 70),
      coordinate("lm", "LM", "MF", 18, 50),
      coordinate("lcm", "CM", "MF", 40, 52),
      coordinate("rcm", "CM", "MF", 60, 52),
      coordinate("rm", "RM", "MF", 82, 50),
      coordinate("cam", "AM", "MF", 50, 35),
      coordinate("lst", "ST", "FW", 40, 18),
      coordinate("rst", "ST", "FW", 60, 18),
    ],
  },
  "5-3-2": {
    name: "5-3-2",
    coordinates: [
      coordinate("gk", "GK", "GK", 50, 88),
      coordinate("lwb", "WB", "DF", 12, 66),
      coordinate("lcb", "CB", "DF", 31, 71),
      coordinate("cb", "CB", "DF", 50, 74),
      coordinate("rcb", "CB", "DF", 69, 71),
      coordinate("rwb", "WB", "DF", 88, 66),
      coordinate("lcm", "CM", "MF", 32, 49),
      coordinate("cm", "CM", "MF", 50, 53),
      coordinate("rcm", "CM", "MF", 68, 49),
      coordinate("lst", "ST", "FW", 40, 20),
      coordinate("rst", "ST", "FW", 60, 20),
    ],
  },
  "5-2-3": {
    name: "5-2-3",
    coordinates: [
      coordinate("gk", "GK", "GK", 50, 88),
      coordinate("lwb", "WB", "DF", 12, 66),
      coordinate("lcb", "CB", "DF", 31, 71),
      coordinate("cb", "CB", "DF", 50, 74),
      coordinate("rcb", "CB", "DF", 69, 71),
      coordinate("rwb", "WB", "DF", 88, 66),
      coordinate("lcm", "CM", "MF", 40, 50),
      coordinate("rcm", "CM", "MF", 60, 50),
      coordinate("lw", "LW", "FW", 20, 24),
      coordinate("st", "ST", "FW", 50, 17),
      coordinate("rw", "RW", "FW", 80, 24),
    ],
  },
  "5-4-1": {
    name: "5-4-1",
    coordinates: [
      coordinate("gk", "GK", "GK", 50, 88),
      coordinate("lwb", "WB", "DF", 12, 66),
      coordinate("lcb", "CB", "DF", 31, 71),
      coordinate("cb", "CB", "DF", 50, 74),
      coordinate("rcb", "CB", "DF", 69, 71),
      coordinate("rwb", "WB", "DF", 88, 66),
      coordinate("lm", "LM", "MF", 18, 46),
      coordinate("lcm", "CM", "MF", 40, 49),
      coordinate("rcm", "CM", "MF", 60, 49),
      coordinate("rm", "RM", "MF", 82, 46),
      coordinate("st", "ST", "FW", 50, 18),
    ],
  },
};

const createTeam = (
  id: string,
  name: string,
  shortName: string,
  formation: FormationName,
  primaryColor: string,
  starters: Player[],
  substitutes: Player[],
  coachName: string,
): TeamLineup => ({
  id,
  name,
  shortName,
  formation,
  primaryColor,
  starters,
  substitutes,
  coach: player(`${id}-coach`, 0, coachName, "Coach"),
});

const emptyPlayerSlot = (id: string, position: PlayerPosition): Player => ({
  id,
  name: "",
  position,
  nationality: "Indonesia",
  countryCode: "ID",
  isForeign: false,
});

const createEmptyTeam = (
  id: string,
  name: string,
  shortName: string,
  formation: FormationName,
  primaryColor: string,
): TeamLineup => ({
  id,
  name,
  shortName,
  formation,
  primaryColor,
  starters: formationTemplates[formation].coordinates.map((slot) =>
    emptyPlayerSlot(`${id}-${slot.id}`, slot.position),
  ),
  substitutes: Array.from({ length: 10 }, (_, index) =>
    emptyPlayerSlot(`${id}-sub-${index + 1}`, "Unknown"),
  ),
  coach: emptyPlayerSlot(`${id}-coach`, "Coach"),
});

const sampleLineupData: MatchdayLineupData = {
  competitionName: "Liga 1 Indonesia",
  matchLabel: "Matchweek 18",
  venue: "GBLA Stadium",
  homeTeam: createTeam(
    "home",
    "Persib Bandung",
    "PERSIB",
    "4-2-3-1",
    "#2563eb",
    [
      player("home-1", 1, "Teja Paku Alam", "GK"),
      player("home-2", 2, "Nick Kuipers", "DF", "🇳🇱", "Netherlands", "NL"),
      player("home-3", 4, "Kakang Rudianto", "DF"),
      player("home-4", 5, "Alberto Rodriguez", "DF", "🇪🇸", "Spain", "ES"),
      player("home-5", 12, "Rezaldi Hehanussa", "DF"),
      player("home-6", 23, "Marc Klok", "MF"),
      player("home-7", 18, "Dedi Kusnandar", "MF"),
      player("home-8", 77, "Ciro Alves", "FW", "🇧🇷", "Brazil", "BR"),
      player("home-9", 10, "Tyronne del Pino", "MF", "🇪🇸", "Spain", "ES"),
      player("home-10", 7, "Beckham Putra", "MF"),
      player("home-11", 19, "David da Silva", "FW", "🇧🇷", "Brazil", "BR"),
    ],
    [
      player("home-sub-1", 14, "Ryan Kurnia", "FW"),
      player("home-sub-2", 16, "Robi Darwis", "MF"),
      player("home-sub-3", 21, "Achmad Jufriyanto", "DF"),
      player("home-sub-4", 30, "Kevin Mendoza", "GK", "🇵🇭", "Philippines", "PH"),
      player("home-sub-5", 97, "Edo Febriansah", "DF"),
      player("home-sub-6", 8, "Abdul Aziz", "MF"),
      player("home-sub-7", 9, "Dimas Drajad", "FW"),
      player("home-sub-8", 27, "Ferdiansyah", "FW"),
      player("home-sub-9", 56, "Rachmat Irianto", "DF"),
      player("home-sub-10", 71, "Fitrul Dwi Rustapa", "GK"),
    ],
    "Bojan Hodak",
  ),
  awayTeam: createTeam(
    "away",
    "Bali United",
    "BALI",
    "4-3-3",
    "#dc2626",
    [
      player("away-1", 1, "Adilson Maringa", "GK", "🇧🇷", "Brazil", "BR"),
      player("away-2", 22, "Novri Setiawan", "DF"),
      player("away-3", 5, "Jajang Mulyana", "DF"),
      player("away-4", 4, "Wellington Carvalho", "DF", "🇧🇷", "Brazil", "BR"),
      player("away-5", 24, "Ardi Idrus", "DF"),
      player("away-6", 8, "Brwa Nouri", "MF", "🇮🇶", "Iraq", "IQ"),
      player("away-7", 6, "Kadek Agung", "MF"),
      player("away-8", 10, "Eber Bessa", "MF", "🇧🇷", "Brazil", "BR"),
      player("away-9", 11, "Yabes Roni", "FW"),
      player("away-10", 9, "Jefferson Assis", "FW", "🇧🇷", "Brazil", "BR"),
      player("away-11", 41, "Privat Mbarga", "FW", "🇨🇲", "Cameroon", "CM"),
    ],
    [
      player("away-sub-1", 17, "I Made Andhika", "DF"),
      player("away-sub-2", 18, "Ricky Fajrin", "DF"),
      player("away-sub-3", 20, "Rahmat", "FW"),
      player("away-sub-4", 33, "Muhammad Ridho", "GK"),
      player("away-sub-5", 91, "Ilija Spasojevic", "FW"),
      player("away-sub-6", 15, "Made Tito", "MF"),
      player("away-sub-7", 26, "Ryuji Utomo", "DF"),
      player("away-sub-8", 28, "Irkham Mila", "FW"),
      player("away-sub-9", 37, "Rizky Pellu", "MF"),
      player("away-sub-10", 88, "Taufik Hidayat", "FW"),
    ],
    "Stefano Cugurra",
  ),
  sponsor: {
    enabled: true,
    brandName: "AWE Media",
  },
};

export const defaultLineupData: MatchdayLineupData = {
  competitionName: "Liga 1 Indonesia",
  matchLabel: "",
  venue: "",
  homeTeam: createEmptyTeam("home", "Home Team", "HOME", "4-2-3-1", "#2563eb"),
  awayTeam: createEmptyTeam("away", "Away Team", "AWAY", "4-3-3", "#dc2626"),
  sponsor: {
    enabled: true,
    brandName: sampleLineupData.sponsor.brandName,
  },
};

export const defaultRumorData: TransferRumorData = {
  player: {
    id: "rumor-player-1",
    name: "Alexis Messidoro",
    position: "MF",
    club: "Persis Solo",
    nationality: "Argentina",
    countryCode: "AR",
    flagEmoji: "🇦🇷",
    isForeign: true,
    transfermarktId: "example-player",
  },
  percentage: 78,
  status: "Advanced Talks",
  fromClub: "Persis Solo",
  toClub: "Dewa United",
  sponsor: {
    enabled: true,
    brandName: "Gosball",
  },
};

export const defaultMatchResultData: MatchResultData = {
  competitionName: competitionMasters[0].name,
  competitionLogoUrl: competitionMasters[0].logoUrl,
  matchLabel: "",
  venue: "",
  status: "FT",
  homeTeam: {
    id: "home-result",
    name: "Home Team",
    shortName: "HOME",
    primaryColor: "#2563eb",
    score: 0,
  },
  awayTeam: {
    id: "away-result",
    name: "Away Team",
    shortName: "AWAY",
    primaryColor: "#dc2626",
    score: 0,
  },
  scorers: [],
  overlayOpacity: 0,
  motm: "",
  note: "",
  sponsor: {
    enabled: true,
    brandName: sampleLineupData.sponsor.brandName,
  },
};
