$f = "d:\Ade Wiramiharja\Aplikasi\Media Tools\src\app\page.tsx"
$lines = [System.IO.File]::ReadAllLines($f, [System.Text.Encoding]::UTF8)

# Replace baris 1523-1588 (0-based: 1522-1587)
$before = $lines[0..1522]
$after  = $lines[1588..($lines.Count - 1)]

$mid = @(
'',
'  // ─────────────────────────────────────────────────────────────────',
'  // REGULASI PEMAIN ASING:',
'  // - Total asing (starting + cadangan DSP) = maks 9',
'  // - Dari 9 itu: maks 7 boleh di starting XI',
'  // - Sisa (9 total - yang masuk starting+cadangan) = Non-DSP, maks 2',
'  // - Cadangan DSP maks 4 total (boleh semua asing asal total asing <= 9)',
'  //   Contoh: 5 starting asing -> cadangan bisa 4 asing (5+4=9)',
'  //           6 starting asing -> cadangan bisa 3 asing (6+3=9)',
'  //           7 starting asing -> cadangan bisa 2 asing (7+2=9)',
'  // ─────────────────────────────────────────────────────────────────',
'  const MAX_SUBS        = 4;   // maks cadangan DSP',
'  const MAX_ASING_TOTAL = 9;   // maks total asing (starting + cadangan)',
'  const MAX_ASING_ST    = 7;   // maks asing di starting XI saja',
'  const MAX_NONDSP      = 2;   // maks asing non-DSP (input manual)',
'',
'  const homeValid = homeStarters.length === 11;',
'  const awayValid = awayStarters.length === 11;',
'  const homeHasGK = homeSquad.some(p => homeStarters.includes(p.id) && p.position === ''Goalkeeper'');',
'  const awayHasGK = awaySquad.some(p => awayStarters.includes(p.id) && p.position === ''Goalkeeper'');',
'  const posLabel: Record<string, string> = { Goalkeeper: ''GK'', Defender: ''DF'', Midfielder: ''MF'', Forward: ''FW'' };',
'',
'  // Klik dari pool -> masuk slot yang tepat secara otomatis',
'  const pickPlayer = (',
'    id: string,',
'    squad: Player[],',
'    starters: string[], setStarters: React.Dispatch<React.SetStateAction<string[]>>,',
'    subs:     string[], setSubs:     React.Dispatch<React.SetStateAction<string[]>>,',
'    asingList: AsingEntry[], setAsing: React.Dispatch<React.SetStateAction<AsingEntry[]>>',
'  ) => {',
'    const player = squad.find(p => p.id === id);',
'    if (!player) return;',
'    const isForeign = player.nationality !== ''Indonesia'';',
'',
'    if (isForeign) {',
'      // Hitung asing yang sudah ada di starting + cadangan DSP',
'      const fSt  = squad.filter(p => starters.includes(p.id) && p.nationality !== ''Indonesia'').length;',
'      const fSub = squad.filter(p => subs.includes(p.id)     && p.nationality !== ''Indonesia'').length;',
'      const fTotal = fSt + fSub; // total asing di DSP (starting+cadangan)',
'',
'      if (fTotal >= MAX_ASING_TOTAL) {',
'        // Sudah 9 asing di DSP -> hanya bisa Non-DSP',
'        if (asingList.length < MAX_NONDSP) {',
'          const entry: AsingEntry = { id: ''nd-'' + id, name: player.displayName, no: player.shirtNumber, pos: posLabel[player.position] || ''MF'' };',
'          setAsing(prev => [...prev, entry]);',
'          triggerToast(player.displayName + '' masuk Non-DSP (kuota 9 asing DSP sudah penuh)'', ''warning'');',
'        } else {',
'          triggerToast(''Kuota asing penuh: 9 DSP + 2 Non-DSP sudah tercapai.'', ''warning'');',
'        }',
'        return;',
'      }',
'',
'      if (starters.length < 11 && fSt < MAX_ASING_ST) {',
'        // Masih ada slot starter dan asing di starter belum 7 -> masuk starting',
'        setStarters(p => [...p, id]);',
'      } else if (starters.length < 11 && fSt >= MAX_ASING_ST) {',
'        // Slot starter ada tapi asing di starting sudah 7 -> masuk cadangan',
'        if (subs.length < MAX_SUBS) {',
'          setSubs(p => [...p, id]);',
'          triggerToast(player.displayName + '' masuk cadangan (maks 7 asing di starting tercapai)'', ''warning'');',
'        } else {',
'          triggerToast(''Cadangan penuh.'', ''warning'');',
'        }',
'      } else {',
'        // Starting sudah 11 -> coba cadangan',
'        if (subs.length < MAX_SUBS) {',
'          setSubs(p => [...p, id]);',
'        } else {',
'          triggerToast(''Semua slot penuh (11 starter + '' + MAX_SUBS + '' cadangan).'', ''warning'');',
'        }',
'      }',
'',
'    } else {',
'      // Pemain lokal: tidak ada batasan khusus',
'      if (starters.length < 11) {',
'        setStarters(p => [...p, id]);',
'      } else if (subs.length < MAX_SUBS) {',
'        setSubs(p => [...p, id]);',
'      } else {',
'        triggerToast(''Semua slot penuh (11 starter + '' + MAX_SUBS + '' cadangan).'', ''warning'');',
'      }',
'    }',
'  };',
'',
'  // Klik di Starting/Cadangan: kembalikan ke pool',
'  const returnToPool = (',
'    id: string,',
'    starters: string[], setStarters: React.Dispatch<React.SetStateAction<string[]>>,',
'    subs:     string[], setSubs:     React.Dispatch<React.SetStateAction<string[]>>',
'  ) => {',
'    if (starters.includes(id)) setStarters(p => p.filter(x => x !== id));',
'    else if (subs.includes(id)) setSubs(p => p.filter(x => x !== id));',
'  };'
)

$newLines = $before + $mid + $after
[System.IO.File]::WriteAllLines($f, $newLines, [System.Text.UTF8Encoding]::new($false))
Write-Host "Patch rules2 OK. Total lines: $($newLines.Count)"
